const onlineResponse = {
  status: true,
  message: "Order created successfully",
  data: {
    userId: "66575ad937b58bb5a83fe8af",
    shippingInfo: {
      firstName: "Sachin",
      lastName: "singh",
      companyName: "School",
      country: "UK",
      streetAddress: { houseNoAndStreetName: "Dhanbad", apartment: "sachin" },
      townCity: "Dhanbad",
      stateCounty: "Jharkhand",
      postcodeZIP: "10001",
      phone: "7254801625",
      email: "sachin19@gmail.com",
      orderNotes: "testing",
      setAsDefault: false,
    },
    items: [
      {
        Product_id: "66572958275c685bed5b78fa",
        Product_title:
          "Dom Perignon Rose, Tiffany & Co. Flute & Godiva Chocolate Gift Set",
        Product_description:
          '<p><strong style="color: rgb(0, 0, 0);">Dom Perignon Rose, Tiffany &amp; Co. Flute &amp; Godiva Chocolate Gift Set</strong></p><p><br></p><p><span style="color: rgb(0, 0, 0);">Treat your loved ones with the Dom Perignon Rosé, Tiffany &amp; Co. Flute, and Godiva Chocolate Gift Set. This stunning collection includes a bottle of Dom Perignon Rosé, celebrated for its rich flavor and vibrant character. Paired with two Tiffany &amp; Co. flutes, it adds a touch of style to any celebration. Completing the set is a selection of Godiva chocolates, offering a wonderful indulgence. Perfect for special occasions or as a memorable gift, this set creates an unforgettable experience. Share a toast, savor fine chocolates, and enjoy moments of true indulgence with this exceptional gift set.</span></p><p><br></p><p><strong style="background-color: transparent; color: rgb(51, 51, 51);">Product Specifications:</strong></p><p><br></p><p><strong style="background-color: transparent; color: rgb(51, 51, 51);">Brands:</strong><span style="background-color: transparent; color: rgb(51, 51, 51);">&nbsp;Dom Perignon,&nbsp;Tiffany Champagne Flute,&nbsp;Godiva</span></p><p><strong style="background-color: transparent; color: rgb(51, 51, 51);">ABV:</strong><span style="background-color: transparent; color: rgb(51, 51, 51);">&nbsp;12.5%</span></p><p><strong style="background-color: transparent; color: rgb(51, 51, 51);">Gift Category:</strong><span style="background-color: transparent; color: rgb(51, 51, 51);">&nbsp;Champagne gift set</span></p><p><strong style="background-color: transparent; color: rgb(51, 51, 51);">Bottle Size:</strong><span style="background-color: transparent; color: rgb(51, 51, 51);">&nbsp;750 ml</span></p><p><strong style="background-color: transparent; color: rgb(51, 51, 51);">Wine Type:</strong><span style="background-color: transparent; color: rgb(51, 51, 51);">&nbsp;Champagne &amp; Sparkling Wine</span></p><p><strong style="background-color: transparent; color: rgb(51, 51, 51);">Varietal:</strong><span style="background-color: transparent; color: rgb(51, 51, 51);">&nbsp;Sparkling Rosé</span></p><p><br></p><p><br></p>',
        Product_category: "CHOCOLATE",
        ProductImg:
          "https://res.cloudinary.com/dnolz4gzn/image/upload/v1716988247/wineProducts/je8dlztcjcr9mjyuqqld.png",
        Product_price: 714,
        Product_quantity: 1,
        Product_totalPrice: 714,
        Product_unit: 1,
        Product_measureUnit: "mL",
        Product_sku: "LUX626",
        _id: "66577ac2ee3efb175615884d",
      },
    ],
    totalPrice: 770.7,
    totalItems: 1,
    paymentMethod: { online: true, cod: false },
    paymentInfo: {
      paymentId: "NY54CpChzfaRCcMqsbvmNeHlYJeZY",
      createdAt: "2024-05-29T18:58:09.771Z",
      updatedAt: "2024-05-29T18:58:10.046Z",
      amountMoney: { amount: 77070, currency: "USD" },
      totalMoney: { amount: 77070, currency: "USD" },
      approvedMoney: { amount: 77070, currency: "USD" },
      status: "COMPLETED",
      receiptNumber: "NY54",
      receiptUrl:
        "https://squareupsandbox.com/receipt/preview/NY54CpChzfaRCcMqsbvmNeHlYJeZY",
      orderId: "GgeGYMUeHpCiL3mJDLwtp3Fu85YZY",
      versionToken: "vjLpP1wywO3umUOKHJnT06HrrDPQmXzm7hZ2DUECb1a6o",
    },
    paidAt: "May 29, 2024 at 6:58 PM",
    trackingDetails: [
      {
        trackingStatus: "Pending",
        trackingDate: "2024-05-29T18:58:10.838Z",
        _id: "66577ac2ee3efb175615884e",
      },
    ],
    orderId: "ORD0012",
    totalShipping: 20,
    totalTax: 36.7,
    price: 770.7,
    orderDate: "2024-05-29T18:58:10.838Z",
    _id: "66577ac2ee3efb175615884c",
    createdAt: "2024-05-29T18:58:10.841Z",
    updatedAt: "2024-05-29T18:58:10.841Z",
    __v: 0,
  },
};

const codRespone = {
  userId: "66537a556fafc56e014f0664",
  shippingInfo: {
    firstName: "sachins",
    lastName: "singh",
    companyName: "sachin",
    country: "UK",
    streetAddress: { houseNoAndStreetName: "sachin", apartment: "sachin" },
    townCity: "dhandbad",
    stateCounty: "dhanbad",
    postcodeZIP: "10001",
    phone: "7254801625",
    email: "sachin@gmail.com",
    orderNotes: "asda",
    setAsDefault: false,
  },
  items: [
    {
      Product_id: "665054e2bca8deb4c5316b5a",
      Product_title: "Veuve Clicquot Brut Yellow Label With Gift Box",
      Product_description:
        "<p>Alcohol is a psychoactive substance found in beverages like beer, wine, and spirits, commonly used for socializing and relaxation, but excessive consumption can lead to health issues and addiction.</p>",
      Product_category: "CHAMPAGNE",
      ProductImg:
        "https://res.cloudinary.com/dnolz4gzn/image/upload/v1716540641/wineProducts/xtmdx5gjdb6xwbu9c2wf.png",
      Product_price: 104,
      Product_quantity: 1,
      Product_totalPrice: 104,
      Product_unit: 2,
      Product_measureUnit: "mL",
      Product_sku: "LUX017",
      _id: "66577c8fee3efb17561592ee",
    },
  ],
  totalPrice: 130.2,
  totalItems: 1,
  paymentMethod: { cod: true, online: false },
  trackingDetails: [
    {
      trackingStatus: "Pending",
      trackingDate: "2024-05-29T19:05:51.995Z",
      _id: "66577c8fee3efb17561592ef",
    },
  ],
  orderId: "ORD0013",
  totalShipping: 20,
  totalTax: 6.2,
  price: 130.2,
  orderDate: "2024-05-29T19:05:51.995Z",
  _id: "66577c8fee3efb17561592ed",
  createdAt: "2024-05-29T19:05:51.999Z",
  updatedAt: "2024-05-29T19:05:51.999Z",
  __v: 0,
};
